### ISSUE TITLE
Host frontend from S3 rather than GitHub Pages

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-db#104]
There are currently two downsides in hosting from GitHub Pages:

- [ ] We cannot differentiate between a UAT and PRD environment, since GitHub Pages only allows one site. The only (cumbersome) way around this would be to host the uat version from a directory, e.g. `nesten.vespawatch.be/uat/`
- [ ] When the app is loaded from the homepage and the user navigates to https://inbo.github.io/vespa-db/table, it works, but directly loading https://inbo.github.io/vespa-db/table does not work (404). Same for https://inbo.github.io/vespa-db/map/observation/3293

@TheJenne18 @stevegerrits do we have more control over this on S3?

**Comment by TheJenne18** [comment]
It could also be an option to deploy the front en the same ecs task but in an other container, specifically for the front-end. @stevegerrits would that be an option for you?

**Comment by peterdesmet** [comment]
@stevegerrits begrijp ik het goed dat de site nu vanuit S3 is gehost? Indien zo, dan mag deze issue gesloten worden.
