### ISSUE TITLE
Rename status in legend and filter

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-db#108]
- [x] Standaard -> Gerapporteerd nest
- [x] Gereserveerd -> Gereserveerd nest
- [x] Bestreden -> Bestreden nest

**Comment by peterdesmet** [comment]
@stevegerrits kan je `nest` toevoegen aan de beschrijving?

**Comment by CatoCoordinator** [comment]
Legende = OK
Filter: Nest status = Niet
![image](https://github.com/user-attachments/assets/7856d858-96ad-4ae1-bd7e-3b7225905504)

**Comment by jrhillae** [comment]
@PietrH: Label fixed

**Comment by peterdesmet** [comment]
Opgelost in legende en filters:
<img width="395" alt="Screenshot 2024-08-27 at 18 26 23" src="https://github.com/user-attachments/assets/6d86c749-3fc4-4d3b-bbb3-07695cb221f8">
