### ISSUE TITLE
ADMIN user type?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-db#110]
Users can be designated:

- [ ] Active
- [ ] Staff status
- [ ] Superuser status

And be of user type: `ADMIN`, `REGULAR`, `SYNC`, `IMPORT`

What is the difference between `ADMIN` and `Superuser status`? Do we even need an `ADMIN` user type?

**Comment by stevegerrits** [comment]
The ADMIN user-type can indeed be removed.
is_staff is used for the admins.
superusers are admins who have all permissions

**Comment by peterdesmet** [comment]
The `ADMIN` status is still present. Reopening.

<img width="147" alt="Screenshot 2024-07-16 at 13 16 31" src="https://github.com/user-attachments/assets/20766b97-e9e6-4ae3-a038-d30383cecd9a">

**Comment by peterdesmet** [comment]
Nu opgelost, geen `ADMIN` meer in dropdown.
