### ISSUE TITLE
Limit width of error message on large screens

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-db#111]
![VespaDB (2)](https://github.com/inbo/vespa-db/assets/600993/5db694a2-b6fc-4600-a996-5f7c5ae138f9)

**Comment by peterdesmet** [comment]
De modal is nog steeds tamelijk breed. Ik zou met col-6 werken.

**Comment by jrhillae** [comment]
Momenteel ziet het er zo uit: 

![image](https://github.com/user-attachments/assets/e0c0b11f-9ef8-4f94-9bb9-bf7ea907297a)

Ik denk ok. Indien nog aan te passen low priority.

**Comment by peterdesmet** [comment]
Dat is nog steeds te breed, ik zet op low priority.

**Comment by peterdesmet** [comment]
Ziet er nu zo uit 👍 

<img width="397" alt="Screenshot 2024-10-02 at 12 04 11" src="https://github.com/user-attachments/assets/f270e7b1-4ba3-494a-8504-80f2b7a89e8b">
