### ISSUE TITLE
Align enums

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-db#114]
Some enums are snake_case, some are English. I think it would be good to align these (also beneficial to users of the API.

I suggest Dutch, ascii and lower snake_case. @jrhillae @CatoCoordinator what do you think?

Current enums:

- [x] nest_height:
  `lager_dan_4_meter`
  `hoger_dan_4_meter`
- [x] nest_size:
  `kleiner_dan_25_cm`
  `groter_dan_25_cm`
- [x] nest_type:
  `actief_embryonaal_nest`
  `actief_primair_nest`
  `actief_secundair_nest`
  `inactief_leeg_nest`
  `potentieel_nest`
- [ ] eradication_product (see #157 instead)
  `Permas-D` => `permas_d`
  `vloeibare_stikstof`
  `Vespa_Ficam_D` => `vespa_ficam_d`
  `Topscore_PAL` => `topscore_pal`
  `ether_aceton_ethyl_acetate` => `ether_aceton_ethyl_acetate`
  `diatomeeënaarde` => `diatomeeenaarde`
  `andere`
- [x] eradication_method:
  `diepvries`
  `telescoopsteel`
  `afsluitbaar potje/doos` => `doos`?
  `vloeistofverstuiver`
  `poederverstuiver`
- [x] eradication_aftercare:
  `nest_volledig_verwijderd`
  `nest_gedeeltelijk_verwijderd`
  `nest_laten_hangen`
- [x] eradication_problems
  `stinging` => `steken`
  `nest_falling` => `nest_gevallen` ??
  `dizziness` => `duizeligheid`
  `poison_projection` => `gif_spuiten` ??

**Comment by jrhillae** [comment]
Dit zijn goede suggesties voor mij.

**Comment by peterdesmet** [comment]
@stevegerrits Ik zie de waarde `ether_aceton_ethyl_acetate` niet meer. Is die verdwenen?

**Comment by CatoCoordinator** [comment]
Bij eradication method zou ik ook nog de optie 'andere' toevoegen (bv. stofzuigmethode)
Bij eradication_problems zou ik ook nog de optie 'geen' toevoegen

**Comment by peterdesmet** [comment]
@CatoCoordinator nee, zie mijn antwoorden in issue #128. `stofzuiger` komt erbij als waarde (#151) en geen problemen = veld leeglaten.

**Comment by peterdesmet** [comment]
testing-failed, `ether_aceton_ethyl_acetate` ontbreekt in `eradication_method`

**Comment by CatoCoordinator** [comment]
Label: Testing-Failed
> Bij 'Bestrijding: Product' staat er nog steeds het volgende (screenshot) i.p.v. onderstaande zoals vermeld door Peter

- Permas-D => permas_d
- vloeibare_stikstof
- Vespa_Ficam_D => vespa_ficam_d
- Topscore_PAL => topscore_pal
- ether_aceton_ethyl_acetate => ether_aceton_ethyl_acetate
- diatomeeënaarde => diatomeeenaarde
- andere

![image](https://github.com/user-attachments/assets/52e12f87-798a-4642-a95f-0b847344f0f8)

**Comment by peterdesmet** [comment]
@CatoCoordinator Er is een verschil tussen de labels (zoals getoond in de dropdown, met hoofdletter en spaties) en de enum values (snake_case).

Wat moet aangepast worden is het consequent met hoofdletter schrijven van de labels.

**Comment by peterdesmet** [comment]
Deze issue is opgelost, de openblijvende taken staan in #157
