### ISSUE TITLE
Test edit and view rights

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-db#119]
Todo: Compare `Vespa DB features` table with what is possible in the application.

- Publiek
- Bestrijder met rechten voor dat gebied
- Vespa DB admin

**Comment by jrhillae** [comment]
@peterdesmet, @PietrH: dit is niet gelukt voor mij om te testen

**Comment by peterdesmet** [comment]
Ik heb dit nu uitgebreid getest, behalve voor export (#132). Er zitten enkele fouten tussen de intenties en verwachtingen, maar voor dat wordt opgelost, moeten we voor een aantal velden een keuze maken:

- [ ] eradicator_name: zou ik publiek maken (want `modified_by` is publiek).
- [ ] eradication_duration: zou ik publiek maken
- [ ] eradication_persons: zou ik publiek maken
- [ ] eradication_result: zou ik publiek maken
- [ ] eradication_method: zou ik publiek maken
- [ ] eradication_product: zou ik publiek maken
- [ ] eradication_aftercare: zou ik publiek maken
- [ ] eradication_problems: zou ik publiek maken
- [ ] eradication_notes: niet publiek, maar dan wel veld verbergen. Beschikbaar voor alle ingelogde gebruikers.
- [ ] wn_notes ("Opmerkingen"): niet publiek, maar dan wel veld verbergen. Beschikbaar voor alle ingelogde gebruikers.
- [ ] wn_validation_status: indien nuttig, publiek (hoe zit dit op wn.be?)
- [ ] wn_admin_notes: indien nuttig, publiek (hoe zit dit op wn.be?)
- [ ] observer_name, observer_email, observer_phone_number: moest staff (#188) hier toegang te krijgen als `personal data niet is aangevinkt`? Moeten `superuser`s dit kunnen aanpassen?
- [ ] wn_cluster_id: indien nuttig, publiek (hoe zit dit op wn.be?) Moeten staff en superusers dit kunnen toekennen?

**Comment by peterdesmet** [comment]
Ik heb de export rechten kunnen testen. Een aantal zaken moeten nog wijzigen, maar momenteel niets kritiek.
