### ISSUE TITLE
Bulk toegang van data via API

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-db#12]
Dit is nodig voor toegang via R voor het exotenportaal. @sanderdevisscher, ik neem aan dat persoonsgegevens van de melder or bestrijder niet nodig zijn voor het exotenportaal?

**Comment by PietrH** [comment]
@SanderDevisscher Hoe wil je die persoonsgegevens verder verwerken in R? Wat wil je daarmee doen?

**Comment by SanderDevisscher** [comment]
@PietrH ik denk hier bijvoorbeeld aan het extracten van email adressen om mails naar te sturen om meer info te bekomen.
