### ISSUE TITLE
Cannot save changes

### ISSUE THREAD

**Issue by DiederikStrubbe** [inbo/vespa-db#122]
tried loggin in with 'gent' and 'Ledeberg'. When I make changes to a nest (e.g. mock details of a nest removal) then I cannot save the changes - nothing seems to happen. When reloading all changes seem to be lost?

**Comment by peterdesmet** [comment]
Thanks @DiederikStrubbe, @stevegerrits is trying to get this resolved. Duplicate of https://github.com/inbo/vespa-db/issues/118
