### ISSUE TITLE
Bestreden nest wordt oranje/geel ipv groen

### ISSUE THREAD

**Issue by CatoCoordinator** [inbo/vespa-db#129]
- [x] probleem 1:
Wanneer je een nest aanduid als 'succesvol bestreden' wordt de kleur op de kaart geel/oranje = kleur van gereserveerd nest i.v.p. groen = kleur van bestreden nest op de kaart.

- [x] probleem 2:
Als bestrijder heb ik het nest eerst gereserveerd. Bovenaan de informatie van het nest komt 'gereserveerd door Stad (nog 5 dagen)' te staan in het oranje/geel = informatie in legende als gereserveerd nest. Dit is OK.
Maar wanneer ik nadien de informatie van het nest onder 'bestrijding' aanpas naar 'succesvol bestreden', dan blijft er bij de titel 'bestrijding' een rode tekst 'bestreden' staan i.p.v. een groene tekst zoals ook in de legende. 

- [ ] probleem 3:
De uitleg van 'gereserveerd door Stad (nog 5 dagen)' blijft dan nog steeds bovenaan onder het nest staan, ookal heb ik het nest aangeduid (en opgeslagen) als 'succesvol bestreden nest'. Dit moet veranderen aangezien het nest 1) bestreden is en 2) ik anders geen andere nesten meer kan reserveren omdat mijn gereserveerde bestreden nesten blijven staan als gereserveerd.
Ik zou zelf nog apart moeten klikken op 'reservatie annuleren'. Dit zou automatisch moeten geannuleerd worden van zodra ik heb aangeduid dat het nest 'succesvol' bestreden is.

**Comment by stevegerrits** [comment]
@peterdesmet kan je even bevestigen dat wanneer een admin of ingelogde gebruiker een nest markeert als bestreden, het nest naar 'bestreden' moet veranderd worden. Was dit in lijn met de logica van het syncronisatie-proces van waarnemingen? Dit veld zal wellicht opnieuw overschreven worden door de sync bij de volgende run

**Comment by peterdesmet** [comment]
Ja, als een nest als bestreden wordt aangeduide door ingelogde gebruiker, dan mag de reservatie opgeheven worden. De bestrijding/reservatie informatie zit niet in waarnemingen.be en kan dus ook niet overschreven worden bij een volgende sync (ofwel begrijp ik de vraag niet goed).

**Comment by stevegerrits** [comment]
@peterdesmet , de reservatie-status updaten kan inderdaad en zal niet overschreven worden door waarnemingen. De bestrijding (Resultaat) zit, als ik me goed herinner, wel in waarnemingen. Dus als de observatie terug ingeladen wordt en waarnemingen deze niet als bestreden heeft aangeduid zal deze opnieuw als 'niet bestreden' worden weergegeven en als niet-gereserveerd. Hierdoor kunnen bestrijders bij al-bestreden nesten toekomen. 

Dit hadden we eerst vermeden met de 'modified_by' logica toe te voegen in de sync. Zodat nesten die geupdate worden op de vespa-db app niet opnieuw kunnen worden overschreven worden door waarnemingen. Dit is er later uitgehaald om alle updates in te laden. Willen we dit opnieuw invoeren? Of extra logica inbouwen nadat een observatie gemarkeerd wordt als bestreden?

**Comment by peterdesmet** [comment]
> De bestrijding (Resultaat) zit, als ik me goed herinner, wel in waarnemingen.

Dat klopt niet, het resultaat zit niet in waarnemingen.be. Het enige wat mogelijk is, is om via het opmerkingen veld een bepaald keyword te gebruiken, waardoor een nest als bestreden moet beschouwd worden. 

1. Als dat keyword aanwezig is, dan mag het nest status op bestreden gezet worden.
2. **Als dat keyword niet aanwezig is, dan mag de nest status niet aangepast worden.**

Alle info van waarnemingen.be mag dus overschreven worden, maar een `NULL` mag in dit geval de status niet wijzigen.

PS: Probleem 2 lijkt opgelost, er komt een groene `bestreden` label.

**Comment by CatoCoordinator** [comment]
Dag Peter, dus een nest dat wordt aangeduid als 'bestreden', kan nadien overschreven worden door 'waarnemingen' info? Ik dacht dat er maar 1x de info van waarnemingen.be naar ons getrokken werd. Of bedoel je dat wanneer die melding is waarnemignen.be nadien wordt gewijzigd en geüpdatet wij die aanpassingen terug naar binnen trekken?

Anders is het wel een probleem dat we de oude info van waarnemingen.be binnentrekken, terwijl onze info dan juist up-to-date is (bv. bestreden ja/nee)

**Comment by peterdesmet** [comment]
Initieel dachten we maar 1x info van waarnemingen.be binnen te trekken, maar dan krijgen we wijzigingen in de locatie of toekenning aan een cluster nooit mee: dat is info die vaak achteraf komt.

Ik denk dat de sync de volgende dingen moet kunnen aanpassen (`ja` = sync mag overschrijven, `nee` = sync past dit veld niet aan).

@CatoCoordinator @jrhillae er staan er een aantal met vraagteken in.
@stevegerrits kan je aanvinken wat al zo is in de applicatie?

- [ ] id: nee
- [ ] wn_id: nee (is de link tussen de 2 systemen)
- [ ] created_datetime: nee
- [ ] modified_datetime: ja (aangepast na sync)
- [ ] location: ja
- [ ] source: nee (blijft hetzelfde)
- [ ] wn_notes: ja
- [ ] wn_admin_notes: ja
- [ ] wn_validation_status: ja
- [ ] species: ja
- [ ] nest_height: ja?
- [ ] nest_size: ja?
- [ ] nest_location: ja?
- [ ] nest_type: ja?
- [ ] observer_phone_number: ja
- [ ] observer_email: ja
- [ ] observer_name: ja
- [ ] observation_datetime: ja
- [ ] wn_cluster_id: ja
- [ ] admin_notes: nee
- [ ] modified_by: nee (blijft hetzelfde)
- [ ] created_by: nee
- [ ] wn_modified_datetime: ja
- [ ] wn_created_datetime: ja
- [ ] visible: misschien, op basis van rules?
- [ ] images: ja
- [ ] reserved_by: nee
- [ ] reserved_datetime: nee
- [ ] eradication_date: ja (= `observation_datetime`, als er een keyword staat in `wn_notes`)
- [ ] eradicator_name: nee
- [ ] eradication_duration: nee
- [ ] eradication_persons: nee
- [ ] eradication_result: nee
- [ ] eradication_product: nee
- [ ] eradication_method: nee
- [ ] eradication_aftercare: nee
- [ ] eradication_problems: nee
- [ ] eradication_notes: nee
- [ ] municipality: ja, automatisch obv `location`
- [ ] province: ja, automatisch obv `location`
- [ ] anb: ja, automatisch obv `location`
- [ ] public_domain: nee
- [ ] observer_received_email: nee

**Comment by CatoCoordinator** [comment]
Vraagtekens hier opgesomd en voorstel:

nest_height: ja          - OK
nest_size: ja              - OK
nest_location: ja       - OK
nest_type: ja             - OK
visible: misschien, op basis van rules?            --> Wat is dit ?

**Comment by peterdesmet** [comment]
`visible` is onze methode om een record niet te tonen op de website, bv. een duplicaat. De enige reden die ik kan bedenken waarbij de waarnemingen.be sync dit veld kan aanpassen is:

> Bij een update heeft een waarneming nu een `wn_cluster_id` die het deelt met een andere record. Dan mag deze waarneming op `visible = FALSE`.

Maar @stevegerrits ik neem aan dat er al zo'n logica is?

**Comment by stevegerrits** [comment]
@peterdesmet  visible wordt gezet op observaties die binnenkomen via waarnemingen en waarvan er een observatie kan gevonden wordt met dezelfde cluster_id die recenter was. (We tonen dus per cluster enkel de recentste observatie)

**Comment by stevegerrits** [comment]
@peterdesmet Even in de code gekeken ivm fields to update. Volgende velden kunnen nu geupdate worden door de sync:

    "location",
    "wn_notes",
    "wn_admin_notes",
    "species",
    "nest_height",
    "nest_size",
    "nest_location",
    "nest_type",
    "observer_phone_number",
    "observer_email",
    "observer_name",
    "observation_datetime",
    "wn_cluster_id",
    "wn_modified_datetime",
    "visible",
    "images",
    "municipality",
    "province",
    "anb",
    
    
    Er zijn dus wel wat velden die bij een eerste sync (creatie) kunnen worden geset, maar niet zullen worden geupdate door de sync. Bijvoorbeeld:  eradication_result, eradication_problems, eradication_method, eradication_product
    
    Voeg ik deze velden toe aan de velden die de sync mag updaten?

**Comment by stevegerrits** [comment]
> > De bestrijding (Resultaat) zit, als ik me goed herinner, wel in waarnemingen.
> 
> Dat klopt niet, het resultaat zit niet in waarnemingen.be. Het enige wat mogelijk is, is om via het opmerkingen veld een bepaald keyword te gebruiken, waardoor een nest als bestreden moet beschouwd worden.
> 
> 1. Als dat keyword aanwezig is, dan mag het nest status op bestreden gezet worden.
> 2. **Als dat keyword niet aanwezig is, dan mag de nest status niet aangepast worden.**
> 
> Info van waarnemingen.be mag via een sync bestaande info dus overschreven (er is concreet maar weinig overlap tussen de velden die de gebruiker kan aanpassen), maar een `NULL` mag geen info vervangen. @CatoCoordinator @jrhillae Als dat overwacht problemen oplevert, moeten we er nog eens over nadenken.
> 
> PS: Probleem 2 lijkt opgelost, er komt een groene `bestreden` label.

@peterdesmet dit klopt inderdaad. Excuses, de enums stonden in de code maar worden idd niet gebruikt/meegegeven door waarnemingen.

**Comment by stevegerrits** [comment]
We kunnen er dus wel vanuit gaan dat als een veld wordt aangeduid als bestreden, dit zo zal blijven en niet door waarnemingen wordt reset.

**Comment by peterdesmet** [comment]
Mooi, als ik je lijst in https://github.com/inbo/vespa-db/issues/129#issuecomment-2233411713 bekijk met wat we op `ja` zetten in https://github.com/inbo/vespa-db/issues/129#issuecomment-2230918576, dan zijn de enige verschillen:

- [ ] modified_datetime: @stevegerrits ik neem aan dat als de sync wijzigt, dit zal aangepast worden?
- [ ] wn_validation_status: @stevegerrits dit veld mag de sync ook wijzigen. Let wel, de enige waarden waartussen dit veld kan wijzigen, zijn waarden statussen die we binnenhalen via de sync. Als de `wn_validation_status` buiten scope valt, dan krijgen we geen updates meer (juist?).
- [ ] eradication_date: @stevegerrits dit gaat terug naar de oorspronkelijke vraag (zie onder)
- [ ] wn_created_datetime: @stevegerrits ik ga ervan uit dat deze niet wijzigt na de eerste sync, maar in principe mag dit veld overschreven worden

## eradication_date

**Create**

1. Een waarneming komt binnen met een keyword in `wn_note`: de waarneming wordt aangemaakt in vespa-db met `eradication_date` == `date(observation_datetime)`

**Update**

1. Een waarneming komt binnen zonder keyword in `wn_notes`: geen `eradication_date`
2. Een gebruiker geeft de waarneming in vespa-db een `eradication_date` of doet dat niet.
3. De waarneming wordt opnieuw gesynced en heeft deze keer wel het keyword in `wn_notes` => geen actie lijkt me het veiligst, de eradication velden kunnen enkel **geüpdated** worden in vespa-db
4. De waarneming wordt opnieuw gesynced en heeft deze keer opnieuw het keyword niet in `wn_notes` => geen actie

**Comment by stevegerrits** [comment]
Er is een check toegevoegd die zal nagaan of de inkomende observatie (in de sync) al een eradication_date heeft ingevuld wanneer in notes BESTREDEN is ingevuld. Enkel indien er nog geen eradication_date is ingevuld zal de sync "eradication_date" invullen op observation_datetime_utc en eradicator_name invullen als "Gemeld als bestreden"

**Comment by CatoCoordinator** [comment]
_**_Label: Closed_**_
> Probleem 3 is opgelost!
