### ISSUE TITLE
Bulk import van data

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-db#13]
Bulk import van data is nuttig voor:

1. Opladen van oude nest data (Vespa-Watch V1, iAsset)
2. Importeren van beheerdata van de brandweer

Het laatste is niet elke het creëren van data, maar het toevoegen van data aan bestaande nesten.

/cc @SanderDevisscher

**Comment by PietrH** [comment]
Verdere databronnen zijn gemeentes en RATO
