### ISSUE TITLE
Ziet niet of wijzigingen succesvol zijn opgeslagen

### ISSUE THREAD

**Issue by CatoCoordinator** [inbo/vespa-db#130]
Wanneer zie je of je aangepaste vakjes succesvol zijn opgeslagen? Ik kan maar blijven klikken op 'wijziging opslaan' en weet niet zeker of het dan wel degelijk is opgeslagen.  Kan dit visueel worden gemaakt? Bv. aangepaste vakjes lichten kort geel op of je krijgt een soort pop-up 'wijzigingen zijn succesvol opgeslagen'.

**Comment by peterdesmet** [comment]
Er is nu een popup, maar de wijzigingen worden niet opgeslagen, zie #118
