### ISSUE TITLE
Export knop werk niet

### ISSUE THREAD

**Issue by DiederikStrubbe** [inbo/vespa-db#132]
Als ik een bepaalde waarneming selecteer, en dan op de export knop duw dan lijkt er niets te gebeuren (noch bij CSV, noch bij JSON).

**Comment by peterdesmet** [comment]
Inderdaad, als de observation details openstaat, werkt de export knop niet.

PS: De export is gebaseerd op de filters, niet op de geselecteerde waarneming.

**Comment by jrhillae** [comment]
@peterdesmet, @PietrH: kan eventueel ook in najaar worden opgelost. Funcionaliteit om data rechtstreeks te downloaden hebben de gemeenten ook niet momenteel.

**Comment by CatoCoordinator** [comment]
Klopt, de export is noodzakelijk voor gemeentes en provincies

**Comment by peterdesmet** [comment]
Knop werkt nu, maar het lijkt me enkel te lukken als ik eerst data filter.

**Comment by peterdesmet** [comment]
Issue closed in favour of #203 and #204.
