### ISSUE TITLE
'niet succesvol behandeld' resulteert nog steeds in status 'bestreden'

### ISSUE THREAD

**Issue by DiederikStrubbe** [inbo/vespa-db#133]
Als ik ingeef als bestrijder ‘niet succesvol behandeld’ dan krijgt het in de tabel nog steeds het label ‘bestreden’, en ook het bolletje blijft groen kleuren.

**Comment by peterdesmet** [comment]
Ik denk dat dit zoals verwacht is? @jrhillae

**Comment by stevegerrits** [comment]
Bij het markeren van bestreden zal de observatie groen kleuren
label van resultaat staat ook op bestreden.
Dit issue mag denk ik gesloten worden

**Comment by jrhillae** [comment]
hier wijst de kleur naar behandeld (al dan niet succesvol) dus ok.
