### ISSUE TITLE
mogelijk om nesten te reserveren buiten het 'eigen gebied'

### ISSUE THREAD

**Issue by DiederikStrubbe** [inbo/vespa-db#135]
Als ik buiten mijn bestrijdingsgebied ga, dan kan ik wel nog nesten reserveren maar niet meer de bestrijdingsstatus aanpassen.

**Comment by peterdesmet** [comment]
@stevegerrits Dit is nu opgelost, maar ik zou de reserveringsknop volledig weglaten, niet disablen zoals nu (want niet erg duidelijk):

<img width="449" alt="Screenshot 2024-07-16 at 12 01 33" src="https://github.com/user-attachments/assets/bded2825-54b3-4647-a14a-4d1369c96f22">

**Comment by CatoCoordinator** [comment]
**Label: Testing-failed**
> Je kan niet meer reserveren buiten Gent = OK
> Je ziet nog steeds de knop 'reserveren'

![image](https://github.com/user-attachments/assets/04f0e5ef-bedd-4e49-b66e-ef63be5995d1)

**Comment by jrhillae** [comment]
@peterdesmet, @PietrH: testing failed maar geen hoge prioriteit.

**Comment by peterdesmet** [comment]
De reserveerknop is nu niet meer zichtbaar waar een gebruiker de rechten niet heeft. 👍
