### ISSUE TITLE
Dezelfde info in legende als nest status in filter

### ISSUE THREAD

**Issue by CatoCoordinator** [inbo/vespa-db#136]
Op legende staan er 3 opties: gerapporteerd, gereserveerd en bestreden.
Om te filteren staat er bij nest status : bestreden, gereserveerd en niet-bestreden.

Dit kan best hetzelfde zijn.

**Comment by stevegerrits** [comment]
@peterdesmet kan dit bekeken worden en daarna doorgeven wat er juist veranderd moet worden?

**Comment by peterdesmet** [comment]
De status moet worden:

```
Gerapporteerd nest
Gereserveerd nest
Bestreden nest
```

Dat is al zo in de legende (maar nog zonder "nest", zie https://github.com/inbo/vespa-db/issues/108), maar nog niet in de filters.

**Comment by CatoCoordinator** [comment]
**Label: Testing-Failed**
Heb op een stuk of 30 nesten geklikt (op map ingelogd als Gent) en alle info bij 'Nest info' is leeg, dus kan dit niet checken
![image](https://github.com/user-attachments/assets/b93164cb-be39-44b3-8bd6-f2b47c9d57b7)

**Comment by jrhillae** [comment]
@peterdesmet, @PietrH : is opgelost
