### ISSUE TITLE
Type nest, wis optie 'potentieel nest'

### ISSUE THREAD

**Issue by CatoCoordinator** [inbo/vespa-db#137]
Alle nesten die hier zichtbaar op zijn waren toch gevalideerd als 'nest Aziatische hoornaar'. Hier kon dacht ik geen twijfel zijn over de soort (wel in platform van waarnemingen.be), toch?

Dit dan wissen bij:
1) Nest info > Type > 'Potentieel nest'
2) Wanneer je op de kaart/Map filtert op nesten > Nest type > 'Potentieel nest (meer info nodig)'

**Comment by stevegerrits** [comment]
@CatoCoordinator je bedoelt dat de filter optie  'Potentieel nest (meer info nodig)' weg mag?

**Comment by peterdesmet** [comment]
@jrhillae klopt het dat het type `Potentieel nest` weg mag omdat we dergelijke waarnemingen niet verwachten?

**Comment by peterdesmet** [comment]
Ik zal toch op hoog zetten, want we willen niet dat gebruikers dit zo aanduiden.

**Comment by peterdesmet** [comment]
Optie `Potentieel` nest niet langer via filters, nest form, api documentatie of admin filters. 👍
