### ISSUE TITLE
Superuser kan niet reserveren

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-db#150]
Als ik inlog als `vespadb` (superuser), dan kan ik geen nesten reserveren. @CatoCoordinator is het nodig dat dit kan?

**Comment by CatoCoordinator** [comment]
Dag Peter,
Zou je nog willen verduidelijken wat het verschil is tussen superuser en andere users? Ik dacht dat er enkel een onderscheid was tussen 
1) Iedereen zonder account 
2) Iedereen met account (provincie en/of gemeente en/of bestrijder)
       a) Toegang om nesten aan te duiden als bestreden
       b) Toegang om nesten te reserveren
       c) Aparte optie door Admin toegewezen: Zien van persoonsgegevens

**Comment by peterdesmet** [comment]
De superuser = ADMIN, maar momenteel wordt dat op 2 plaatsen gedefineerd:

1. Als een user van type REGULAR (= human) met rechten `superuser
2. Als een user van type `ADMIN`

Dat laatste moet weg, want het is verwarrend met het eerste.

**Comment by CatoCoordinator** [comment]
Vooral provincies, gemeentes en bestrijders moeten nesten kunnen reserveren.
@jrhillae en ik gaan dat niet doen. Dus het is OK als wij die optie niet hebben

**Comment by peterdesmet** [comment]
Superuser (Vespa db) had de knop `reserveren` beschikbaar. Deze werkt nu ook (zelfs mocht die niet gebruikt worden). 👍
