### ISSUE TITLE
Beschrijvende waarden voor Product

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-db#157]
De enum waarden voor `eradication_product` staat beschreven in https://github.com/inbo/vespa-db/issues/114. De beschrijvende waarden in de dropdown moeten nog wat aangepast worden:

<img width="264" alt="Screenshot 2024-07-19 at 09 11 47" src="https://github.com/user-attachments/assets/5f397f52-da15-4090-9dd5-f22abbbd74ee">

- [x] `Geen`
- [x] `Permas-D`
- [x] `Vloeibare stikstof` (met hoofdletter)
- [ ] `Vespa Ficam D` splitsen:
  - [x] `VESPA` (API/DB: `vespa`)
  - [x] `Ficam D` (API/DB: `ficam_d`)
- [x] `Topscore PAL` (niet Topscore_PAL)
- [x] `Diatomeeënaarde` (niet diatomeeenaarde)
- [x] `Ether, aceton of ethylacetaat` toevoegen (al aanwezig in API/DB als `ether_aceton_ethyl_acetate`
- [x] `Andere` (met hoofdletter)

**Comment by CatoCoordinator** [comment]
Label: testing failed

**Comment by jrhillae** [comment]
@peterdesmet: ik denk dat Vespa Ficam D eigenlijk de 2 producten VESPA en Ficam D zijn die per ongeluk zijn samengevoegd op 1 lijn in plaats van afzonderlijk

**Comment by jrhillae** [comment]
@peterdesmet, @PietrH  : dit corrigeren door Steven is voor mij geen "high priority" want Permas D en diamtomeëenaarde zijn meest toegepaste producten in het veld en deze staan er reeds duidelijk in.

**Comment by peterdesmet** [comment]
Waarden staan nu juist. API enum is ook ok. 👍
