### ISSUE TITLE
Corrigeer meervoud Municipality in admin

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-db#158]
In de Admin zou het meervoud zou als `Municipalities` geschreven moeten worden (is wel juist in de API):

<img width="287" alt="Screenshot 2024-07-19 at 09 19 30" src="https://github.com/user-attachments/assets/2267e6f3-0a4c-4103-b66b-90bbb8ea040c">

**Comment by CatoCoordinator** [comment]
**Label: Close**
Staat indd 'Municipalties'
