### ISSUE TITLE
Add Admin filter `By observer received email`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-db#159]
Cf. `By anb`, graag een `By observer received email` filter in de Admin voor de observations. Deze filter gebruikt het veld `observer_received_email`

<img width="259" alt="Screenshot 2024-07-19 at 09 44 01" src="https://github.com/user-attachments/assets/7b314caa-f2ec-412a-9d74-2b49a0ed24ea">

**Comment by CatoCoordinator** [comment]
Label: Close
Je kan inderdaad nu filteren bij 'BY anb: All/Yes/No' of ze een email hebben ontvangen of niet 'By Observer Received: EmailAll/Yes/No'.
![image](https://github.com/user-attachments/assets/2840e16d-40ca-4c14-b22c-9f7ccd6fb2bd)
![image](https://github.com/user-attachments/assets/b0fbc2b1-45e7-48f3-9c43-416c42ee933b)

Ook kan je bij Action: Verzend email naar observatoren doen

**Comment by stevegerrits** [comment]
Vraag: Wordt dan automatisch het vakje 'Observer received email' aangevinkt in de waarneming? Kan ik dit testen zonder dat de waarnemer een email krijgt?
-> dit zou inderdaad het geval moeten zijn. Echter is het verzenden van de emails not niet geimplementeerd.
