### ISSUE TITLE
Hoofdletters in nest type waarden

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-db#160]
De dropdown waarden voor nest type zijn de enige die niet met hoofdletter worden geschreven. Ik zou dit aanpassen. De enum waarden in de API mogen blijven zoals ze zijn:

<img width="384" alt="Screenshot 2024-07-19 at 09 49 24" src="https://github.com/user-attachments/assets/6288cf2e-8b2b-4602-b167-89058b042467">

`actief embryonaal nest` -> `Actief embryonaal nest` etc.

**Comment by CatoCoordinator** [comment]
Gelukt -> **Close issue** (Heb geen knop om de issues af te sluiten, enkel een comment knop)
