### ISSUE TITLE
Filter op kaart en tabel verschilt

### ISSUE THREAD

**Issue by CatoCoordinator** [inbo/vespa-db#163]
Wanneer je filtert in 'tabel' op 'nest status: gereserveerd' krijg je het aantal gereserveerde nesten te zien (die ik in dit geval heb gereserveerd omdat ik ben ingelogd met Gent).
= OK
![image](https://github.com/user-attachments/assets/10f95409-bc87-497c-8db2-d5154a5af928)

Wanneer ik dan terug naar 'map' ga, zie ik dan enkel nog die ene reservatie staan, maar als ik dan op 'filter' klik zijn alle filters leeg en is er zogezegd niet gefilterd op 'nest status: gereserveerd' maar dit is dus wel het geval.
![image](https://github.com/user-attachments/assets/e0625855-d1ff-478e-aa57-2b66aea2e791)

**Comment by jrhillae** [comment]
@PietrH : kan je high priority label hieraan toewijzen? Bedankt

**Comment by peterdesmet** [comment]
1. Filter on map `Aalter`
2. Only records from `Aalter` are shown on map 👍 
3. Navigate to table
4. Only records from `Aalter` are shown in table 👍 
5. The filter window is empty 👎 (does not show `Aalter`)
6. Select `Aarschot`
7. Only records from `Aarschot` are shown in table 👍 
8. Navigate to map
9. Only records from `Aarschot` are shown on map 👍 

In general, I feel that the filter window doesn't always show the correct information. E.g. here a filter for two municipalities is shown, while only one appears in the filter window:
<img width="857" alt="Screenshot 2024-09-19 at 16 18 09" src="https://github.com/user-attachments/assets/ea351303-e10d-42a9-bb7f-9451e1745f59">
