### ISSUE TITLE
duur in min ipv uren

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-db#169]
@peterdesmet: In de oude databank is duur steeds uitgedruk in minuten bijvoorbeeld 00:40:00. Pas ik de oude databank aan naar uren voor het opladen of passen we de eenheiden van duur in vespadb aan naar minuten? Het laatste lijkt mij logischer 0.5 uur of 30 min ;)

**Comment by peterdesmet** [comment]
Ik denk dat jij beter kan inschatten hoelang een interventie meestal duurt. Als dat gemakkelijker uit te drukken valt in minuten (bv. 150 ipv 2.5u) dan kunnen we aanpassen. We namen uur omdat dit meer standaard is.

Laat maar weten.

**Comment by jrhillae** [comment]
Best minuten dan.

**Comment by peterdesmet** [comment]
@steveritz aanpassingen voor `eradication_duration`:

- type: integer (zie #116)
- placeholder: `bv. 30 (min)` ipv `bv. 0.5 (uur)`

**Comment by peterdesmet** [comment]
Juist in API en frontend. 👍
