### ISSUE TITLE
Nest type met hoofdletter

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-db#170]
Nest type heeft als enige variabele attributen zonder hoofdletter in het keuzemenu. Low priority.

**Comment by peterdesmet** [comment]
Ik zie ze met hoofdletter:

<img width="391" alt="Screenshot 2024-08-27 at 18 22 41" src="https://github.com/user-attachments/assets/45d37176-e4f2-4434-a939-77ed60e73ffd">

 Ik sluit dit issue.

**Comment by peterdesmet** [comment]
Sorry, ze staan inderdaad met kleine letters in de filter en dat is aan te passen:

<img width="401" alt="Screenshot 2024-08-27 at 18 24 39" src="https://github.com/user-attachments/assets/bffa393b-c9ef-4564-933f-80a400b825c9">
