### ISSUE TITLE
Steeds waarnemingenID gebruiken als ID 

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-db#171]
Overal waar ID wordt vermeld wordt nu een ID uit VespaDB gebruikt maar dit zou best de ID uit waarneming.be databank zijn. In elke communicatie met melder en bestrijder wordt namelijk verwezen naar de waarnemingenID. Deze waarde wordt binnenkort ook duidelijk vermeld in de mail naar melder na rapportage, met vraag deze duidelijk te vermelden bij elke communicatie. De ID uit VespaDB databank mag verscholen zijn @PietrH: high priority

Aan te passen:
- kaart 
![image](https://github.com/user-attachments/assets/1e210a6e-65a0-46d6-b526-e3969343a3b0)

- tabel
![image](https://github.com/user-attachments/assets/6a0880b0-647e-4e1b-a0d8-d0ef019a45f2)

- admin
![image](https://github.com/user-attachments/assets/0d4d7b76-6737-4b94-a4f4-e60256a58b0e)

**Comment by peterdesmet** [comment]
We kunnen niet zomaar verbergen:

- Niet elke melding zal via waarnemingen.be komen, ze kunnen ook geïmporteerd worden.
- De URL gebruikt momenteel ook de interne ID: https://uat-nesten.vespawatch.be/#/map/observation/2819

We moeten dus een andere oplossing vinden.

**Comment by peterdesmet** [comment]
@jrhillae niet het eerste voorstel (dat wordt heel verwarrend in de databank), wel het tweede.

> duidelijke naamgeving geven aan ID en waarnemingenID zodat verschil duidelijk is? Bv vespawatchID en waarnemingenID

Dit is vooral van belang in de API. Daar hebben we nu `id` en `wn_id`. Ik zou dat zou behouden.

> waarnemingenID ook toevoegen aan de tabel?

Ja, ik heb het toegevoegd in https://github.com/inbo/vespa-db/issues/174#issuecomment-2312608993

> wanneer je klikt op een melding beide ID's tonen?

Ik stel het volgende voor:

<img width="457" alt="Screenshot 2024-09-05 at 13 07 17" src="https://github.com/user-attachments/assets/dc31c781-c2ca-46f8-8b61-5520540bb169">

**Comment by jrhillae** [comment]
> @jrhillae niet het eerste voorstel (dat wordt heel verwarrend in de databank), wel het tweede.
> 
> > duidelijke naamgeving geven aan ID en waarnemingenID zodat verschil duidelijk is? Bv vespawatchID en waarnemingenID
> 
> Dit is vooral van belang in de API. Daar hebben we nu `id` en `wn_id`. Ik zou dat zou behouden.
> 
> > waarnemingenID ook toevoegen aan de tabel?
> 
> Ja, ik heb het toegevoegd in [#174 (comment)](https://github.com/inbo/vespa-db/issues/174#issuecomment-2312608993)
> 
> > wanneer je klikt op een melding beide ID's tonen?
> 
> Ik stel het volgende voor:
> 
> <img alt="Screenshot 2024-09-05 at 13 07 17" width="457" src="https://private-user-images.githubusercontent.com/600993/364753084-dc31c781-c2ca-46f8-8b61-5520540bb169.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzkzNzYsIm5iZiI6MTcyNTUzOTA3NiwicGF0aCI6Ii82MDA5OTMvMzY0NzUzMDg0LWRjMzFjNzgxLWMyY2EtNDZmOC04YjYxLTU1MjA1NDBiYjE2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxMjI0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzUxYzMwNTkxODY3ZWYyMzcwNWJkMjUzMGY2ZjM1MDQ5NGU4NmNkMTEyNjljOTRhZWNmODBhNWU1N2JmZDUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4j8-tPU9NhvYus8nIyKIonZz6L6Xig0axi54QPgOEMc">

Dit ziet er heel goed uit!

**Comment by peterdesmet** [comment]
@steveritz indien `wn_id != NULL`, graag de nest details aanpassen zoals in screenshot hierboven (met `target="_blank"` voor de link). De tabel pakken we aan in #174.

**Comment by peterdesmet** [comment]
Ziet er goed uit en link werkt:

<img width="397" alt="Screenshot 2024-09-19 at 16 28 45" src="https://github.com/user-attachments/assets/10e25c89-4103-40b9-b2af-10470ddf2260">
