### ISSUE TITLE
Zoekbalk op adres toevoegen aan kaart

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-db#173]
High priority: Een zoekbalk op basis van adres is noodzakelijk voor een bestrijder om snel in te zoomen naar het nest dat hij heeft bestreden die dag.

**Comment by peterdesmet** [comment]
Is toegevoegd en werkt heel vlot:

<img width="610" alt="Screenshot 2024-09-19 at 16 29 54" src="https://github.com/user-attachments/assets/dfe71747-4411-452f-abd1-f3eca65f56ec">
