### ISSUE TITLE
Toevoegen public domain aan frontend

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-db#175]
Voor rapportage aan VMM is het belangrijk dat een bestrijder kan aangeven of een nest al dan niet in openbaar domein ligt. In de beheerregeling staat dat we de rapportage van bestreden nesten in publiek domein op ons nemen. Daarom is het veld public domain best zichtbaar aan frontend zodat het kan worden aangepast door een bestrijder bij de bestrijdingsinfo. @PietrH: high priority

**Comment by steveritz** [comment]
public_domain kan aangepast worden door alle ingelogde gebruikers

**Comment by peterdesmet** [comment]
Veld staat nu op de juiste plaats:

<img width="409" alt="Screenshot 2024-09-19 at 16 32 22" src="https://github.com/user-attachments/assets/b5a7a547-9964-466b-bc32-fe890452cfb5">

Maar ik zou rechten - net zoals alle velden - bepreken tot ingelogde gebruiker binnen dat gebied.
