### ISSUE TITLE
Te checken bij API

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-db#177]
@peterdesmet, @PietrH:Een paar opmerkingen/vragen bij de API van Waarnemingen:

- [x] Alex bevestigde dat **goedgekeurd (door admin)** een verouderde term is, dit wordt momenteel genoemd: **goedgekeurd (aannemelijk)**. De API documentatie van waarnemingen was verouderd en gebruikte nog de oude term. Kan dit worden aangepast in vespa-db?

In de export vind ik voor alle nesten een waarde, ofwel:

```
goedgekeurd_met_bewijs
goedgekeurd_door_admin
```

Ik zou deze waarden behouden.

- [x] BESTREDEN kan zowel worden vermeld in [kolom 'notes' als kolom 'attributes_5_value'](https://docs.google.com/spreadsheets/d/1gVrPeMj74pDkHd5oQJ8fmlMRAP5Dh85SManUzLI1eJQ/edit?gid=0#gid=0) (deze laatste kolom noemt niet zo in documentatie maar heb ik er aangegeven bij uitpakken van de waarden). Ik maakte zelf de fout om BESTREDEN eerst op 'notes' te baseren maar het moet vooral 'attributes_5_value' zijn. @Steven, welke waarde gebruik jij momenteel?

@stevegerrits dit lijkt nog niet te werken, maar er is een aparte issue voor #211

- [x] Mogelijks is dit mijn fout in script of een fout bij de API zelf maar de volgorde van de attributes 1 tot 5 blijkt soms te wijzigen bij inlezen API. Zie [deze file ](https://docs.google.com/spreadsheets/d/1gfldDQAO1-se1_8NDULL6QU_JboEhq1BrrZ3lqBmmOc/edit?gid=0#gid=0) als voorbeeld rij 21 (in geel aangeduid). Ligt de fout bij mij en moet mijn script hierop voorbereid zijn? Ik ging er tot nu van uit dat de volgorde van de attributes gelijk is per observatie.

De sync gebruikt niet de volgorde, maar de namen van de attributen. Meerdere binnenkomende waarden worden gemapt op 1 waarde.

- [x] Nest type (attribute 4): Op vraag van vrijwilligers zijn de keuzeopties binnen nest type verduidelijkt met een beschrijving. De waarde zelf blijkt echter te zijn aangepast in API. Hoe op te lossen? Toen ik dit Alex vroeg zei hij eerst van niet en dat de kolom attribute_4_value wel ongewijzigd blijft maar deze refereert enkel naar 'nest type' en niet naar de keuzeopties binnen 'nest type.

Dit gaat momenteel fout, maar er is een aparte issue voor https://github.com/inbo/vespa-db/issues/263

- [x] e-mail is te halen uit de kolommen admin_notes en email. Dit was een bug langs waarnemingenAPI zijde, Alex ging dit oplossen zodat ze enkel uit kolom email te halen zijn.

**Comment by peterdesmet** [comment]
@jrhillae voor het eerste: vooral `attributes_5_value` of enkel `attributes_5_value`? Wat is beter?

**Comment by jrhillae** [comment]
@Peter: Beide want notes is voor meldingen die via persoonlijke accounts komen (bij validatie kunnen validatoren hier info toevoegen zoals de term BESTREDEN) en 'attributes_5_value' voor meldingen via event pagina.

**Comment by peterdesmet** [comment]
@steveritz kan je even antwoorden op de vragen in https://github.com/inbo/vespa-db/issues/177#issue-2471435873? Indien onduidelijk, dan kan ik verduidelijken via chat.

**Comment by steveritz** [comment]
Ik maakte zelf de fout om BESTREDEN eerst op 'notes' te baseren maar het moet vooral 'attributes_5_value' zijn. @steven, welke waarde gebruik jij momenteel?
 --> @peterdesmet  bedoel je bij de sync?
 
 Zijn er voor de rest nog vragen?

**Comment by peterdesmet** [comment]
> @peterdesmet bedoel je bij de sync?

Ja, bij de sync. En op basis van https://github.com/inbo/vespa-db/issues/177#issuecomment-2331048067 moeten we het dus op 2 velden baseren: `wn_notes` en `attributes$notes`

> Zijn er voor de rest nog vragen?

Ja, zie issue body. Afchecken als Vespa-DB hier juist mee omgaat:

- [ ] `wn_validation_status` geeft nieuwe waarde terug via waarnemingen API
- [ ] Worden `attributes` ingelezen op basis van naam of volgorde. Volgorde is niet te vertrouwen
- [ ] `nest_type` geeft nieuwe waarde terug via waarnemingen API

**Comment by steveritz** [comment]
@peterdesmet voor de sync gebruiken we inderdaad enkel 'notes'. Als hier het woord 'bestreden' in voorkomt. 

Dit moet dus, als ik het goed begrijp, aangepast worden. attributes_5_value moet hier aan toegevoegd worden? Ook op 'bestreden' nagaan?
---
wn_validation_status : wordt ingevuld door de sync
attributes worden ingelezen/gemapped dmv naam  (nest_type zit hier bij en moet dus normaal ook geupdate worden. Dat is toch wat je met "geeft nieuwe waarde terug" bedoelt hé, dat het wordt geupdate?)

**Comment by steveritz** [comment]
@jrhillae @peterdesmet wat wordt bedoeld met  'attributes_5_value' ?

Dit is voorbeeld-data die ik terug krijg van waarnemingen:

`{'id': 327453457, 'date': '2024-09-08', 'time': '14:50:00', 'point': {'type': 'Point', 'coordinates': [4.914156943564223, 50.783467968041805]}, 'accuracy': 3, 'species': 212573, 'activity': 95, 'life_stage': 1056, 'method': 738, 'validation_status': 'J', 'notes': None, 'admin_notes': '', 'created': '2024-09-08T14:52:06.449439', 'modified': '2024-09-08T14:52:51.491109', 'attributes': [], 'nest': None, 'photos': ['https://waarnemingen.be/media/photo/104125724.jpg'], 'source': 'iObs', 'source_event': None, 'user': {'id': 140365, 'name': 'Jef Verhoeven', 'email': None, 'phone_number': None}}`

**Comment by peterdesmet** [comment]
> voor de sync gebruiken we inderdaad enkel 'notes'. Als hier het woord 'bestreden' in voorkomt. Dit moet dus, als ik het goed begrijp, aangepast worden. attributes_5_value moet hier aan toegevoegd worden? Ook op 'bestreden' nagaan?

Klopt, `notes` en/of `attributes.xxx` bevat een van de sleutelwoorden (momenteel enkel `bestreden`). Ik weet niet welke naam het veld `xxx` heeft. We kunnen niet afgaan op het 5de veld in `attributes`, dat moet op naam (cf. `nest_type`) @jrhillae wat is de naam van dit attribuutveld?

> attributes worden ingelezen/gemapped dmv naam (nest_type zit hier bij en moet dus normaal ook geupdate worden. Dat is toch wat je met "geeft nieuwe waarde terug" bedoelt hé, dat het wordt geupdate?)

- `attributes.nest_type` heeft nog steeds dezelfde (veld)naam
- de waarden van dit veld zijn een enum. In principe zou dit ongewijzigd moeten blijven aan de wn.be kant, maar we zijn niet zeker dat dit zo is (i.e. het label is gewijzigd, misschien is de enum waarde ook gewijzigd). Wat is de impact op Vespa-DB als een enum waarde wijzigt?

**Comment by steveritz** [comment]
@peterdesmet: ivm enum wijzigingen waarnemingen:  de sync zal de nieuwe enums niet kunnen mappen.

**Comment by peterdesmet** [comment]
Er zijn geen openstaande issues hier die niet elders worden behandeld.
