### ISSUE TITLE
Bestrijdingsinfo

### ISSUE THREAD

**Issue by CatoCoordinator** [inbo/vespa-db#180]
Low priority:

Bestrijding
Nest info

Aanpassen naar

Bestrijdingsinfo
Nest info

![image](https://github.com/user-attachments/assets/c55dffa8-140c-4789-8e9b-d55dd872a59d)

**Comment by peterdesmet** [comment]
Het lijkt me vreemd om het ene woord met en het andere zonder spatie te gebruiken. Zelf zou ik het op `bestrijding` houden.
