### ISSUE TITLE
Bulk reserveren

### ISSUE THREAD

**Issue by CatoCoordinator** [inbo/vespa-db#181]
Ik kan geen nesten als bulk reserveren.
Bv. Ik ben gemeente Gent en sta in om alle nesten op mijn grondgebied te bestrijden, dan zou ik elk nest apart moeten aanduiden als 'reserveren'.
Ik weet dat er limieten zijn (max. 50 nesten), maar zou dit mogelijk zijn via kaart of tabel ?

**Comment by peterdesmet** [comment]
Bulk reservatie voor bestrijders is by design niet toegelaten. Er is ook een limiet. Als dit wel nodig is, dan lijkt me dat een v1.1. feature.
