### ISSUE TITLE
Actie 'verzend email naar observatoren' werkt niet

### ISSUE THREAD

**Issue by CatoCoordinator** [inbo/vespa-db#183]
Heb bij ID 9167 test het emailadres vespawatch@vlaanderen.be ingezet en daar een email naar verzonden (op 21/08/2024), maar deze is nooit aangekomen.

Ook vandaag geprobeerd maar niets ontvangen

**Comment by peterdesmet** [comment]
Maybe related to #86

**Comment by steveritz** [comment]
@peterdesmet @CatoCoordinator  Verzenden van emails moet nog worden geimplementeerd.
