### ISSUE TITLE
Kolom en/of filter aanmaken op 'modified date'

### ISSUE THREAD

**Issue by CatoCoordinator** [inbo/vespa-db#202]
@steveritz  en @peterdesmet 

Zorgen voor een kolom en/of filter voor 'modified date' waarbij je kan zien wie het heeft aangepast, zodat je kan raadplegen welke nesten het laatst zijn aangepast geweest en door wie.
Dit is handig bij bijvoorbeeld foutjes in aanpassingen

**Comment by peterdesmet** [comment]
Ter info: dit is voor het Observations overzicht in de Django admin module.
