### ISSUE TITLE
Geen JSON export aanbieden

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-db#203]
De JSON export is momenteel invalid:

```
[object Object],[object Object],[object Object],[object Object],[object Object],...
```

- [ ] Eerder dan een JSON export aan te bieden, kunnen we beter linken naar de observations API:

<img width="194" alt="Screenshot 2024-09-23 at 14 04 42" src="https://github.com/user-attachments/assets/3cc0bdeb-8b75-4892-9841-8126578fe7f6">

De `API` kan linken naar https://uat-db.vespawatch.be/swagger/#operations-observations-observations_list

- [ ] Daarnaast zou ik `json` niet ondersteunen als `export_format` in `observations/export`

**Comment by peterdesmet** [comment]
Wat is het verschil tussen de `observations` en `observations/export` API?

**Comment by steveritz** [comment]
@peterdesmet met json export is er geen verschil. Heb de json disabled in de fe
