### ISSUE TITLE
Filter professional, bestreden en gevalideerde nesten komen niet uit excel

### ISSUE THREAD

**Issue by CatoCoordinator** [inbo/vespa-db#205]
@jrhillae , er zijn nu al een aantal nesten die niet in de datastroom van waarnemingen.be tot vespa-Watch komen. Zou je naar de filters kunnen kijken en nagaan door wat het komt?

Enkele voorbeelden:

1. [329086821   - https://waarnemingen.be/observation/329086821/](https://waarnemingen.be/observation/328711271/)
Dit nest is gevalideerd (met bewijs) maar komt niet in de flow terecht van West-Vlaanderen. Deze heb ik handmatig toegevoegd.

2. melding 321616375 bevat het woord 'bestreden', maar deze komt nog in de datastroom om nog te verdelgen.

Groetjes,

Cato

**Comment by jrhillae** [comment]
@CatoCoordinator: 

1. ik heb het nest uit de flow gedaan en de code gelopen, het nest wordt nu aan West-Vlaanderen toegewezen. Ik heb geen idee waarom het dus eerst niet werkte. Mss stond 1 van de settings (nest, in Vlaanderen, AH met bewijs) nog niet juist op moment dat het script liep? Of had de info tijd nodig om via de API van waarnemingen beschikbaar te zijn? Het werkt wel op dit moment in ieder geval.
2. 'bestreden' moet steeds in hoofdletters: 'BESTREDEN'
3. professional heeft geen filter in het script. Deze meldingen moeten manueel worden opgezocht en gevalideerd, zie [validatorhandleiding](https://docs.google.com/document/d/14279xWNNgWJ7YYun5GtxcaAnNgC90i_PiYXGRzeWlZ0/edit#heading=h.bi65liygzp3u), vraag 8 (Hoe meldingen valideren die zonder foto door een bestrijder zijn gemeld?)
