### ISSUE TITLE
Gevalideerde nesten Hasselt komen niet door

### ISSUE THREAD

**Issue by CatoCoordinator** [inbo/vespa-db#235]
Dag @jrhillae 

Kan je nagaan hoe het komt dat volgende nesten niet doorkomen in het script voor Hasselt?

https://waarnemingen.be/observation/330928920/ 

https://waarnemingen.be/observation/331819874/

Bedankt!

Groeten

Cato

**Comment by jrhillae** [comment]
@CatoCoordinator : is het ok voor jou om deze issue op vespaR te plaatsen en Soria te taggen? Ik ben op verlof volgende week en heb nog veel af te werken vandaag.
