### ISSUE TITLE
External API response proposal

### ISSUE THREAD

**Issue by stevegerrits** [inbo/vespa-db#5]
```json
{
  "id": 1,
  "point": {
    "type": "Point",
    "coordinates": [
      4.182466,
      51.007389
    ],
    "uncertainty": 3
  },
  "created": "2023-10-19T00:21:41Z",
  "modified": "2023-10-19T00:34:51Z",
  "attributes": [
    {
      "name": "nest_type",
      "value": "primair"
    }
  ],
  "created_by": "account_name_validator",
  "observations": [
    {
      "id": 123450604,
      "date": "2023-10-19",
      "time": "00:21:41",
      "species": 456,
      "validated": "A",
      "notes": "Pidgey nest",
      "admin_notes": null,
      "source": "event-page",
      "created": "2023-10-17T08:00:00Z",
      "modified": "2023-10-17T08:00:00Z",
      "observer": {
        "name": "Peter Desmet",
        "email": "peter.desmet@inbo.be",
        "telephone": null
      },
      "attributes": [
        {
          "name": "nest_height",
          "value": "+4m"
        },
        {
          "name": "nest_size",
          "value": "-25cm"
        },
        {
          "name": "nest_location",
          "value": "outside_building"
        }
      ],
      "images": [
        "https://img.pokemondb.net/artwork/pidgey.jpg"
      ]
    },
    {}
  ]
}
```

**Comment by PietrH** [comment]
Great job summarizing. 

- I really like the pokemon mocks. 
- Are you aware of the darwincore term coordinateUncertaintyInMeters? https://dwc.tdwg.org/list/#dwc_coordinateUncertaintyInMeters
- I believe we are expecting name, value, id pairs for the attributes
- I'm unsure we'll get image comments or id's, the id's are probably going to be part of the url anyway. 
- For observations date and time will be seperate fields, time will be a local time

**Comment by stevegerrits** [comment]
@PietrH It's a quick draft to express my idea of the external-api response, not all fields etc are correct/included yet. I can make this one complete if we want to go further with this ofc!

Was not aware of the darwincore, this ppoint value was a copy/paste from the word doc "Vespa Watch waarnemingen.nl API docs feedback"

**Comment by peterdesmet** [comment]
I have updated the issue body to correct some mistakes
