### ISSUE TITLE
Get email service account credentials 

### ISSUE THREAD

**Issue by stevegerrits** [inbo/vespa-db#86]

**Comment by peterdesmet** [comment]
@stevegerrits can you let me know what config parameters you need?

**Comment by peterdesmet** [comment]
@stevegerrits we decided that emails should be send from `noreply@vespawatch.be`.

@berthuygens will update the MX record for vespawatch.be to point to AWS. Do you need credentials then to use this email address?

**Comment by peterdesmet** [comment]
@berthuygens informed me that this email address `noreply@vespawatch.be` has been created on AWS, @stevegerrits @TheJenne18? If so, can you close this ticket?
