### ISSUE TITLE
remove observations of individuals 

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-db#97]
@stevegerrits: Ik ben de API ook aan het uittesten in R. En via de observations url krijg je ook observaties van wespen ookal is er geen nest gemeld. Zoals deze: https://waarnemingen.be/observation/313439504/. Dit is een koningin die is gemeld, maar geen nest. Maar je krijgt het toch als resultaat via observations url. Je kan deze van elkaar onderscheiden via activity. Bij nesten worden activity door validatoren op nest gezet.

**Comment by peterdesmet** [comment]
@stevegerrits er is nu een filter op de waarnemingen API om enkel nesten binnen te krijgen:

https://waarnemingen.be/api/v1/inbo/vespa-watch/observations/?activity=3240&activity=3036&activity=xxxx

De laatste code moeten we nog opvragen

**Comment by jrhillae** [comment]
https://waarnemingen.be/api/v1/species-groups/17/attributes/

de laatste code is 3241 (nestbouw)

**Comment by PietrH** [comment]
Set to enhancement by Jasmijns request :+1:

**Comment by peterdesmet** [comment]
Opgelost in productie en UAT lijkt me.
