### ISSUE TITLE
swagger documentation: TypeError + can't get examples to work

### ISSUE THREAD

**Issue by PietrH** [inbo/vespa-db#98]
I had a look at the swagger documentation of the api: https://uat-db.vespawatch.be/swagger/

Should I be able to run the examples in the documentation? I can't get a list of municipalities for example

![image](https://github.com/inbo/vespa-db/assets/48065851/06ec9206-372b-4391-b861-6600d69545b0)

If the documentation examples only work when you authenticate, then we might as well just provide static examples. 

Also note the type error/network error

I also noticed some calls don't have parameters documented, this is a bit confusing to me; Does that mean I don't need to provide any parameters? 

![image](https://github.com/inbo/vespa-db/assets/48065851/7ac57e73-1733-487a-a98e-457019b6c5ab)

**Comment by PietrH** [comment]
I just retried, still get the same error

**Comment by peterdesmet** [comment]
I could now successfully `execute` on endpoints without credentials (like municipalities):

<img width="1212" alt="Screenshot 2024-07-16 at 10 04 54" src="https://github.com/user-attachments/assets/e966c513-103b-4d87-a698-276da9a91e3c">

And I get an expected error message for those that require authentication:

<img width="1207" alt="Screenshot 2024-07-16 at 10 05 08" src="https://github.com/user-attachments/assets/64710a36-ca52-4579-afbb-f092fc273945">
